version: '3.8'
services:
  gateway:
    build: gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root

  postgresql:
    image: postgres:13.8-alpine
    container_name: postgresql_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root